# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TaxReader' do
  use_frameworks!
  # 忽略引入库的所有警告
  inhibit_all_warnings!
  source 'https://github.com/CocoaPods/Specs.git'
  
  #pod 'YYKit'
  pod 'SVProgressHUD'
  pod 'ESTabBarController-swift', '~> 2.7'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SVProgressHUD'
  pod 'MJRefresh', '~> 3.2.0'
  pod 'MJExtension'
  pod 'Kingfisher', '~> 5.7.0'
  pod 'SDWebImage'
  pod 'TPKeyboardAvoiding', '~> 1.3.2'
  pod 'Moya', '~> 14.0.0-alpha.1'
  pod 'HandyJSON', '~> 5.0.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'ZZCryptManager'
  
  pod 'FSPagerView', '~> 0.8.2'
  pod 'SnapKit', '~> 5.0.0'
  pod 'DNSPageView', '~> 1.0.1'
  
  pod 'BTCaptchaView', '~> 1.0.4'
  
  pod 'ObjectMapper'
  pod 'Chrysan', :git => 'https://github.com/Harley-xk/Chrysan.git'
  
  pod 'CryptoSwift'
  pod 'SwiftDate' 
end

